ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}

# RUN ./bin/logstash-plugin install logstash-filter-date_formatter

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
